# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];
 
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/90943879-88c6-4694-b9fa-2dbe5f959b0a";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D41A-D27B";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/838abdfd-a0ca-40fc-bb77-1560f05a0ac3"; }
    ];

  # fileSystems / swapDevices are provided by ./disko.nix.

  networking.useDHCP = lib.mkDefault true;
  hardware.rtl-sdr.enable = true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
